### ISSUE TITLE
NPE when viewing an empty `aes` file

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook-dev-desktop#55]
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
	at org.fxmisc.richtext.model.ReadOnlyStyledDocument.fromString(ReadOnlyStyledDocument.java:99)
	at org.fxmisc.richtext.GenericStyledArea.replaceText(GenericStyledArea.java:1196)
	at org.fxmisc.richtext.EditActions.replaceText(EditActions.java:148)
	at lockbook.dev.EditorUi.$anonfun$loadFile$2(EditorUi.scala:45)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

**Comment by Parth** [comment]
See `mistakes.aes`
